### ISSUE TITLE
GA 1 und GA2

### ISSUE THREAD

**Issue by schmaiki** [Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung#146]
Hallöchen.

Haste aber schick gemacht, schon mal Daumen hoch. 
Mir ist aufgefallen das du GA1 und GA2 hast. Das gibt es nicht mehr.
Es ist jetzt so aufgebaut:
 
## Abschlussprüfung Teil 1

- Einrichten eines IT-gestützten Arbeitsplatzes644

## Abschlussprüfung Teil 2

- Planen eines Softwareproduktes
- Entwicklung und Umsetzung von Algorithmen!

## Betriebliche Projektarbeit

- Präsentation und Fachgespräch
- Planen und Umsetzen eines Softwareprojektes!

Bei Fragen stehe ich dir sehr gern zur Verfügung. 
LG Maiki

**Comment by LNA-DEV** [comment]
Stimmt. Die Bzeichnungen sind jetzt anders :+1: 

Werde ich bei Gelegenheit ändern. Danke @schmaiki :smile:

**Comment by MustafaDemiroglu** [comment]
Themen sind gut sortiert

**Comment by LNA-DEV** [comment]
Werde das doch nicht ändern, da die Teile nach wie vor Ganzheitliche Aufgaben heisen. Sie sind jetzt nur beide fachspezifisch.

Denke die aktuelle Sortierung sollte dann ganz gut passen :smile:

**Comment by MaikPeters1511** [comment]
Wo soll das stehen

**Comment by LNA-DEV** [comment]
@MaikPeters1511 Stimmt habe zu oberflächlich geschaut. In der Prüfung werden die Begriffe gar nicht mehr verwendet.

Abundzu sehe ich noch das "Berufsspezifsiche Aufgaben" verwendet wird. Habe das in den Titeln nachgezogen. Die Ordnerstruktur lasse ich fürs erste so. Da müssten sonst viele Aliase gesetzt werden.
