### ISSUE TITLE
Datenschutz und Impressum nicht erreichbar

### ISSUE THREAD

**Issue by anthonyhfm** [Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung#159]
Mir ist gerade aufgefallen dass man ein 404 Not Found Error bekommt wenn man auf die Datenschutzrichtlinie oder das Impressum verwiesen werden will

![image](https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung/assets/76816347/ccefe75e-22cf-4732-a677-e7c295a2eb85)

**Comment by LNA-DEV** [comment]
Danke für die Info :+1:
