### ISSUE TITLE
RAID - Redundant array of independent disks

### ISSUE THREAD

**Issue by DerWaldFried** [Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung#171]
In diesem Kapitel funktioniert das erste Video nicht mehr -> RAID 0,1,5 erklärt = Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: kgFfn_GJ9GbcfBOp)

Das Video scheint entfernt. Folgt man dem Link, so kommt die Hauptseite von YouTube

**Comment by LNA-DEV** [comment]
Vielen Dank für die Info :+1:
